name: flutter_app
description: Um novo projeto Flutter para gerenciamento de estatísticas, calendário e uploads.

publish_to: 'none' # Remova essa linha se for publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0         # Para requisições HTTP à API
  file_picker: ^9.2.0     # Para selecionar arquivos (vídeos) no dispositivo
  image_picker: ^1.1.2    # Para selecionar imagens no dispositivo
  path_provider: ^2.0.2   # Para acessar o sistema de arquivos do dispositivos
  google_fonts: any
  table_calendar: ^3.2.0
  video_player: ^2.9.3
  intl: ^0.20.2
  image_picker_linux: ^0.2.1+2
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/background_home.png
    - assets/images/diretoria_soon.png
    
  
