name: daza_fc_app
description: Um novo projeto Flutter para gerenciamento de estatísticas, calendário e uploads.

publish_to: 'none' # Remova essa linha se for publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0         # Para requisições HTTP à API
  file_picker: ^9.2.1     # Para selecionar arquivos (vídeos) no dispositivo
  video_player: ^2.9.3
  intl: ^0.20.2
  table_calendar: ^3.1.0
  image_picker: ^1.0.4
  flutter_lints: ^5.0.0  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
assets:
  - assets/images/logo.png
  - assets/images/background.png
  - assets/images/background_home.png
  - assets/images/diretoria_soon.png